package reporter

import (
	"fmt"
	"io"
	"strings"

	"github.com/opscart/k8s-cost-optimizer/pkg/models"
)

// GenerateMarkdown creates a Markdown report
func GenerateMarkdown(report *Report, writer io.Writer) error {
	var sb strings.Builder

	// Header
	sb.WriteString("# 📊 K8s Cost Optimizer Report\n\n")
	sb.WriteString(fmt.Sprintf("**Cluster:** %s  \n", report.ClusterName))
	if report.Namespace != "" {
		sb.WriteString(fmt.Sprintf("**Namespace:** %s  \n", report.Namespace))
	} else {
		sb.WriteString("**Namespace:** All Namespaces  \n")
	}
	sb.WriteString(fmt.Sprintf("**Generated:** %s  \n\n", report.GeneratedAt.Format("January 2, 2006 15:04:05 MST")))

	// Executive Summary
	sb.WriteString("## 📈 Executive Summary\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| **Total Monthly Savings** | **$%.2f** |\n", report.TotalSavings))
	sb.WriteString(fmt.Sprintf("| Workloads Analyzed | %d |\n", report.WorkloadCount))
	sb.WriteString(fmt.Sprintf("| Optimization Opportunities | %d |\n\n", report.OptimizableCount))

	// Environment Breakdown
	if len(report.EnvironmentStats) > 0 {
		sb.WriteString("## 🏢 By Environment\n\n")
		sb.WriteString("| Environment | Workloads | Recommendations | Monthly Savings |\n")
		sb.WriteString("|-------------|-----------|-----------------|------------------|\n")
		for _, envStat := range report.EnvironmentStats {
			sb.WriteString(fmt.Sprintf("| %s | %d | %d | $%.2f |\n",
				strings.ToUpper(envStat.Environment),
				envStat.WorkloadCount,
				envStat.Recommendations,
				envStat.TotalSavings,
			))
		}
		sb.WriteString("\n")
	}

	// Detailed Recommendations
	sb.WriteString("## 📋 Detailed Recommendations\n\n")
	sb.WriteString("| Workload | Environment | Type | Current | Recommended | Savings | Risk |\n")
	sb.WriteString("|----------|-------------|------|---------|-------------|---------|------|\n")

	for _, rec := range report.Recommendations {
		workloadName := fmt.Sprintf("%s/%s", rec.Workload.Namespace, rec.Workload.Deployment)
		currentResources := fmt.Sprintf("%dm CPU, %dMi RAM", rec.CurrentCPU, rec.CurrentMemory/(1024*1024))
		recommendedResources := fmt.Sprintf("%dm CPU, %dMi RAM", rec.RecommendedCPU, rec.RecommendedMemory/(1024*1024))

		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | $%.2f | %s |\n",
			workloadName,
			rec.Environment,
			rec.Type,
			currentResources,
			recommendedResources,
			rec.SavingsMonthly,
			rec.Risk,
		))
	}
	sb.WriteString("\n")

	// Top Savings Opportunities
	sb.WriteString("## 💰 Top Savings Opportunities\n\n")
	// Sort by savings (top 5)
	topRecs := getTopRecommendations(report.Recommendations, 5)
	if len(topRecs) > 0 {
		for i, rec := range topRecs {
			sb.WriteString(fmt.Sprintf("%d. **%s/%s** - $%.2f/month\n",
				i+1,
				rec.Workload.Namespace,
				rec.Workload.Deployment,
				rec.SavingsMonthly,
			))
			sb.WriteString(fmt.Sprintf("   - Type: %s | Risk: %s\n", rec.Type, rec.Risk))
			if rec.Reason != "" {
				sb.WriteString(fmt.Sprintf("   - Reason: %s\n", rec.Reason))
			}
			sb.WriteString("\n")
		}
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [k8s-cost-optimizer](https://github.com/opscart/k8s-cost-optimizer)*\n")

	// Write to output
	_, err := writer.Write([]byte(sb.String()))
	return err
}

// getTopRecommendations returns top N recommendations by savings
func getTopRecommendations(recs []*models.Recommendation, n int) []*models.Recommendation {
	// Create a copy to avoid modifying original
	sorted := make([]*models.Recommendation, len(recs))
	copy(sorted, recs)

	// Simple bubble sort by savings (descending)
	for i := 0; i < len(sorted)-1; i++ {
		for j := 0; j < len(sorted)-i-1; j++ {
			if sorted[j].SavingsMonthly < sorted[j+1].SavingsMonthly {
				sorted[j], sorted[j+1] = sorted[j+1], sorted[j]
			}
		}
	}

	// Return top N
	if n > len(sorted) {
		n = len(sorted)
	}
	return sorted[:n]
}
