package executor

import (
	"fmt"
	"strings"

	"github.com/opscart/k8s-cost-optimizer/pkg/recommender"
)

// GenerateCommand creates a kubectl command for a recommendation
func GenerateCommand(rec *recommender.Recommendation) string {
	switch rec.Type {
	case recommender.RightSize:
		return generateRightSizeCommand(rec)
	case recommender.ScaleDown:
		return generateScaleDownCommand(rec)
	default:
		return ""
	}
}

func generateRightSizeCommand(rec *recommender.Recommendation) string {
	cpuRequest := fmt.Sprintf("%dm", rec.RecommendedCPU)
	memRequest := fmt.Sprintf("%dMi", rec.RecommendedMemory/(1024*1024))

	// Set limits to 2x requests for burstability
	cpuLimit := fmt.Sprintf("%dm", rec.RecommendedCPU*2)
	memLimit := fmt.Sprintf("%dMi", rec.RecommendedMemory*2/(1024*1024))

	// Get workload resource type (deployment, statefulset, daemonset)
	resourceType := getResourceType(rec.WorkloadType)

	return fmt.Sprintf(
		"kubectl set resources %s/%s -n %s --requests=cpu=%s,memory=%s --limits=cpu=%s,memory=%s",
		resourceType, // Changed from "deployment" to dynamic
		rec.DeploymentName,
		rec.Namespace,
		cpuRequest,
		memRequest,
		cpuLimit,
		memLimit,
	)
}

func generateScaleDownCommand(rec *recommender.Recommendation) string {
	resourceType := getResourceType(rec.WorkloadType)

	return fmt.Sprintf(
		"kubectl scale %s/%s -n %s --replicas=0",
		resourceType, // Changed from "deployment" to dynamic
		rec.DeploymentName,
		rec.Namespace,
	)
}

// getResourceType converts workload type to kubectl resource type
func getResourceType(workloadType string) string {
	switch workloadType {
	case "StatefulSet":
		return "statefulset"
	case "DaemonSet":
		return "daemonset"
	case "ReplicaSet":
		return "replicaset"
	case "Deployment":
		return "deployment"
	default:
		return "deployment" // default fallback
	}
}

// GenerateScript creates a bash script with all commands
func GenerateScript(recommendations []*recommender.Recommendation) string {
	var sb strings.Builder

	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Generated by k8s-cost-optimizer\n")
	sb.WriteString("# Review carefully before executing\n\n")
	sb.WriteString("set -e\n\n")

	totalSavings := 0.0

	for _, rec := range recommendations {
		if rec.Type == recommender.NoAction {
			continue
		}

		sb.WriteString(fmt.Sprintf("# %s: %s\n", rec.DeploymentName, rec.Reason))
		sb.WriteString(fmt.Sprintf("# Savings: $%.2f/month | Impact: %s | Risk: %s\n",
			rec.Savings, rec.Impact, rec.Risk))
		sb.WriteString(GenerateCommand(rec))
		sb.WriteString("\n\n")

		totalSavings += rec.Savings
	}

	sb.WriteString(fmt.Sprintf("# Total savings: $%.2f/month\n", totalSavings))

	return sb.String()
}
