---
# Idle deployment - barely uses any resources
# Should be identified as wasteful
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idle-app
  namespace: cost-test
  labels:
    app: idle
    team: frontend
    environment: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: idle
  template:
    metadata:
      labels:
        app: idle
        team: frontend
        environment: test
    spec:
      containers:
      - name: sleeper
        image: busybox:latest
        command: ["sleep", "infinity"]
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
