---
# Reasonably sized deployment - good baseline
apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-app
  namespace: cost-test
  labels:
    app: normal
    team: backend
    environment: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: normal
  template:
    metadata:
      labels:
        app: normal
        team: backend
        environment: test
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80
